"""
Evidence pre-scoring: fast, deterministic signal extraction.

Runs BEFORE any LLM call. Scores articles on artifact likelihood
using keyword matching, URL presence, jurisdiction signals,
lifecycle indicators, and crime severity signals.
"""

from __future__ import annotations

import re

# Lazy import to avoid circular deps at module load
_jurisdiction_portals = None


def _get_portals():
    global _jurisdiction_portals
    if _jurisdiction_portals is None:
        from archive.jurisdiction_portals import (
            JURISDICTION_PORTALS,
            is_florida_case,
            has_court_video,
        )
        _jurisdiction_portals = {
            "portals": JURISDICTION_PORTALS,
            "is_florida": is_florida_case,
            "has_court_video": has_court_video,
        }
    return _jurisdiction_portals


# ---------------------------------------------------------------------------
# Keyword banks
# ---------------------------------------------------------------------------

ARTIFACT_KEYWORDS = {
    # ---- Body-worn / officer camera ----
    "bodycam": 15,
    "body cam": 15,
    "body-cam": 15,
    "bodycam footage": 15,
    "bodycam video": 15,
    "body-worn camera": 15,
    "body worn camera": 15,
    "body-worn video": 15,
    "body worn video": 15,
    "bwc": 15,
    "bwc footage": 15,
    "officer camera": 12,
    "officer's camera": 12,
    "police video": 12,
    "police footage": 12,
    "officer video": 12,
    "lapel camera": 12,
    "lapel cam": 12,
    "chest camera": 10,
    "worn camera": 10,
    "police camera": 12,
    "cop cam": 10,
    "officer-worn": 10,
    # ---- Dash / in-car camera ----
    "dashcam": 15,
    "dash cam": 15,
    "dash-cam": 15,
    "dashcam footage": 15,
    "dashcam video": 15,
    "dash camera": 15,
    "in-car camera": 15,
    "in-car video": 15,
    "in car camera": 15,
    "in car video": 15,
    "patrol car video": 12,
    "patrol car camera": 12,
    "patrol car footage": 12,
    "cruiser camera": 12,
    "cruiser video": 12,
    "cruiser footage": 12,
    "squad car camera": 12,
    "squad car video": 12,
    "mvr": 10,  # mobile video recorder
    "mobile video recorder": 12,
    # ---- Interrogation / interview ----
    "custodial interview": 15,
    "custodial interrogation": 15,
    "interrogation video": 15,
    "interrogation tape": 15,
    "interrogation footage": 15,
    "interrogation recording": 15,
    "interrogation room": 12,
    "interview room": 10,
    "police interview": 12,
    "police interrogation": 15,
    "detective interview": 12,
    "detective interrogation": 12,
    "confession video": 15,
    "confession tape": 15,
    "confession recording": 15,
    "recorded confession": 12,
    "recorded interview": 10,
    "recorded interrogation": 12,
    "recorded statement": 10,
    "videotaped confession": 15,
    "videotaped interrogation": 15,
    "videotaped interview": 12,
    "taped confession": 12,
    "taped interrogation": 12,
    "taped interview": 10,
    "suspect interview": 10,
    "witness interview": 8,
    # ---- Surveillance / security ----
    "surveillance footage": 15,
    "surveillance video": 15,
    "surveillance camera": 12,
    "surveillance tape": 12,
    "surveillance recording": 12,
    "surveillance system": 8,
    "security camera": 12,
    "security footage": 12,
    "security video": 12,
    "security tape": 10,
    "security recording": 10,
    "security camera footage": 15,
    "store camera": 10,
    "store surveillance": 10,
    "store video": 8,
    "parking lot camera": 10,
    "parking lot video": 10,
    "parking garage camera": 10,
    "atm camera": 10,
    "atm footage": 10,
    "gas station camera": 10,
    "gas station video": 10,
    "bank camera": 10,
    "bank surveillance": 10,
    "bank video": 10,
    "lobby camera": 8,
    "elevator camera": 8,
    "hallway camera": 8,
    "traffic camera": 10,
    "traffic cam": 10,
    "red light camera": 8,
    "license plate reader": 8,
    "lpr": 6,
    "alpr": 6,
    "cctv": 12,
    "cctv footage": 15,
    "cctv video": 12,
    "closed circuit": 10,
    "closed-circuit": 10,
    "ring doorbell": 12,
    "ring camera": 12,
    "ring video": 12,
    "doorbell camera": 12,
    "doorbell footage": 12,
    "doorbell video": 12,
    "nest camera": 10,
    "nest cam": 10,
    "arlo camera": 8,
    "wyze camera": 8,
    "home security camera": 10,
    "home surveillance": 10,
    "home security": 8,
    "home camera": 8,
    "residential camera": 8,
    "trail camera": 8,
    "trail cam": 8,
    "game camera": 6,
    "nanny cam": 8,
    "baby monitor": 6,
    # ---- Court / trial video ----
    "trial livestream": 15,
    "trial live stream": 15,
    "trial stream": 12,
    "court video": 15,
    "courtroom video": 15,
    "courtroom footage": 15,
    "courtroom camera": 12,
    "court footage": 15,
    "court camera": 12,
    "court livestream": 15,
    "court live stream": 15,
    "court stream": 12,
    "court tv": 12,
    "courttv": 10,
    "law & crime": 10,
    "law and crime": 10,
    "law&crime": 10,
    "gavel to gavel": 12,
    "gavel-to-gavel": 12,
    "trial video": 15,
    "trial footage": 15,
    "trial broadcast": 12,
    "trial coverage": 8,
    "trial camera": 12,
    "sentencing video": 15,
    "sentencing footage": 15,
    "sentencing hearing video": 15,
    "arraignment video": 12,
    "hearing video": 12,
    "hearing footage": 12,
    "deposition video": 12,
    "deposition tape": 10,
    "televised trial": 12,
    "televised hearing": 10,
    "televised sentencing": 12,
    "cameras in the courtroom": 10,
    "courtroom cameras": 10,
    # ---- Bystander / citizen / social media ----
    "cell phone video": 12,
    "cellphone video": 12,
    "cell phone footage": 12,
    "cellphone footage": 12,
    "mobile phone video": 12,
    "smartphone video": 10,
    "bystander video": 12,
    "bystander footage": 12,
    "bystander recorded": 10,
    "onlooker video": 10,
    "witness video": 10,
    "witness recorded": 8,
    "caught on camera": 12,
    "caught on tape": 12,
    "caught on video": 12,
    "caught on film": 10,
    "captured on camera": 12,
    "captured on video": 12,
    "recorded on camera": 10,
    "filmed the incident": 10,
    "filmed the encounter": 10,
    "filmed the arrest": 12,
    "recorded the incident": 10,
    "recorded the encounter": 10,
    "recorded the arrest": 12,
    "facebook live": 10,
    "facebook video": 8,
    "instagram live": 10,
    "instagram video": 8,
    "tiktok video": 8,
    "snapchat video": 8,
    "live streamed": 8,
    "livestreamed": 8,
    "live-streamed": 8,
    "viral video": 8,
    "video went viral": 8,
    "video has gone viral": 8,
    # ---- Audio evidence ----
    "911 call": 12,
    "911 calls": 12,
    "911 audio": 12,
    "911 recording": 12,
    "911 tape": 12,
    "911 dispatch": 10,
    "emergency call": 10,
    "emergency calls": 10,
    "dispatch audio": 10,
    "dispatch recording": 10,
    "dispatch call": 8,
    "radio traffic": 8,
    "radio transmission": 8,
    "police radio": 8,
    "scanner audio": 8,
    "jailhouse call": 12,
    "jailhouse calls": 12,
    "jailhouse recording": 12,
    "jailhouse phone call": 12,
    "jail call": 10,
    "jail calls": 10,
    "jail recording": 10,
    "jail phone call": 10,
    "prison call": 10,
    "prison phone call": 10,
    "prison recording": 10,
    "inmate call": 10,
    "inmate phone call": 10,
    "phone call recording": 10,
    "recorded phone call": 10,
    "wiretap": 12,
    "wire tap": 12,
    "phone tap": 10,
    "audio recording": 8,
    "audio evidence": 10,
    "audio tape": 8,
    # ---- Aerial / other visual ----
    "helicopter footage": 10,
    "helicopter video": 10,
    "chopper footage": 8,
    "chopper video": 8,
    "news chopper": 8,
    "news helicopter": 8,
    "aerial footage": 10,
    "aerial video": 10,
    "aerial view": 6,
    "drone footage": 10,
    "drone video": 10,
    "overhead footage": 8,
    "overhead video": 8,
    "sky cam": 6,
    # ---- Crime scene / forensic ----
    "crime scene photos": 10,
    "crime scene video": 12,
    "crime scene footage": 12,
    "crime scene images": 8,
    "crime scene photographs": 10,
    "evidence photos": 8,
    "evidence video": 10,
    "autopsy photos": 10,
    "autopsy report": 8,
    "forensic evidence": 8,
    "forensic video": 10,
    "forensic analysis": 6,
    "dna evidence": 6,
    "ballistic evidence": 6,
    "toxicology report": 6,
    "medical examiner": 6,
    "coroner report": 6,
    "coroner's report": 6,
    # ---- Documents / records ----
    "court documents": 8,
    "court records": 8,
    "court filings": 8,
    "police report": 8,
    "police reports": 8,
    "incident report": 8,
    "arrest report": 8,
    "arrest affidavit": 10,
    "arrest warrant": 8,
    "search warrant": 8,
    "probable cause affidavit": 10,
    "probable cause statement": 10,
    "criminal complaint": 8,
    "charging document": 8,
    "indictment": 8,
    "grand jury indictment": 10,
    "public records": 6,
    "public records request": 8,
    "foia": 8,
    "foia request": 8,
    "freedom of information": 8,
    "open records": 6,
    "open records request": 8,
    "sunshine law": 8,
    "body camera policy": 6,
    # ---- Generic release / availability language ----
    "released video": 12,
    "released footage": 12,
    "released the video": 12,
    "released the footage": 12,
    "released body": 10,  # "released bodycam" partial
    "released dash": 10,  # "released dashcam" partial
    "police released": 10,
    "department released": 10,
    "sheriff released": 10,
    "da released": 8,
    "agency released": 8,
    "officials released": 8,
    "authorities released": 10,
    "newly released": 12,
    "just released": 10,
    "obtained video": 10,
    "obtained footage": 10,
    "obtained by": 6,
    "exclusively obtained": 8,
    "video shows": 8,
    "footage shows": 8,
    "video captures": 8,
    "footage captures": 8,
    "video reveals": 8,
    "footage reveals": 8,
    "video depicts": 8,
    "footage depicts": 8,
    "can be seen": 5,
    "can be heard": 5,
    "video evidence": 10,
    "video released": 12,
    "footage released": 12,
    "made public": 6,
    "publicly available": 6,
    "available online": 5,
    # ---- Press / public statement ----
    "press conference": 10,
    "news conference": 10,
    "press briefing": 8,
    "media briefing": 8,
    "press release": 6,
    "public statement": 5,
}

VIDEO_PLATFORMS = {
    # Major
    "youtube.com": 20,
    "youtu.be": 20,
    "youtube.com/watch": 20,
    "youtube.com/live": 20,
    "youtube.com/shorts": 15,
    "vimeo.com": 15,
    # Alt-video
    "rumble.com": 10,
    "dailymotion.com": 10,
    "bitchute.com": 8,
    "odysee.com": 8,
    "streamable.com": 10,
    "v.redd.it": 8,
    "worldstarhiphop.com": 6,
    # Social with video
    "facebook.com/watch": 8,
    "facebook.com/reel": 8,
    "fb.watch": 8,
    "tiktok.com": 5,
    "twitter.com/i/status": 5,
    "x.com/i/status": 5,
    "instagram.com/reel": 5,
    "instagram.com/p/": 5,
    # Legal / court streaming
    "courtlistener.com": 10,
    "law.com": 6,
    "casetext.com": 6,
    "pacer.gov": 8,
    "recap.law": 6,
    # News video embeds
    "cnn.com/video": 8,
    "nbcnews.com/video": 8,
    "abcnews.go.com/video": 8,
    "cbsnews.com/video": 8,
    "foxnews.com/video": 8,
}

LIFECYCLE_KEYWORDS = {
    # ---- Conviction / sentencing ----
    "sentenced": 5,
    "sentenced to": 5,
    "sentencing": 5,
    "sentencing hearing": 5,
    "convicted": 5,
    "convicted of": 5,
    "conviction": 5,
    "found guilty": 5,
    "guilty verdict": 5,
    "jury convicted": 5,
    "life sentence": 5,
    "life in prison": 5,
    "life without parole": 5,
    "lwop": 5,
    "consecutive sentences": 5,
    "concurrent sentences": 4,
    "death penalty": 5,
    "death sentence": 5,
    "death row": 5,
    "without parole": 5,
    "years in prison": 4,
    "years to life": 5,
    "maximum sentence": 5,
    "minimum sentence": 4,
    "mandatory minimum": 4,
    # ---- Plea ----
    "guilty plea": 5,
    "plea deal": 5,
    "plea agreement": 5,
    "plea bargain": 5,
    "plea offer": 4,
    "plea hearing": 4,
    "pleaded guilty": 5,
    "pled guilty": 5,
    "pleads guilty": 5,
    "entered a plea": 4,
    "entered a guilty plea": 5,
    "entered guilty plea": 5,
    "changed his plea": 5,
    "changed her plea": 5,
    "accepted a plea": 5,
    "pleaded no contest": 5,
    "pled no contest": 5,
    "nolo contendere": 3,
    "alford plea": 5,
    "cooperation agreement": 4,
    "cooperating witness": 4,
    # ---- Trial ----
    "trial": 5,
    "trial date": 4,
    "trial began": 5,
    "trial begins": 5,
    "trial underway": 5,
    "on trial": 5,
    "went to trial": 5,
    "going to trial": 4,
    "stands trial": 5,
    "stand trial": 4,
    "verdict": 5,
    "jury verdict": 5,
    "not guilty": 4,
    "acquitted": 4,
    "acquittal": 4,
    "hung jury": 5,
    "mistrial": 5,
    "retrial": 4,
    "jury deliberation": 5,
    "jury deliberated": 5,
    "jury returned": 4,
    "jury found": 5,
    "jury selection": 4,
    "voir dire": 4,
    "jury trial": 5,
    "bench trial": 5,
    "closing arguments": 5,
    "closing argument": 5,
    "opening statements": 5,
    "opening statement": 5,
    "testimony": 4,
    "testified": 4,
    "testify": 3,
    "witness testimony": 4,
    "expert testimony": 4,
    "witness testified": 4,
    "took the stand": 5,
    "on the stand": 4,
    "cross-examination": 4,
    "cross examination": 4,
    "cross-examined": 4,
    "direct examination": 3,
    "redirect examination": 3,
    "exhibit": 2,
    "evidence presented": 4,
    "state rested": 4,
    "defense rested": 4,
    "prosecution rested": 4,
    # ---- Pre-trial ----
    "indicted": 3,
    "indictment": 3,
    "superseding indictment": 4,
    "arraigned": 3,
    "arraignment": 3,
    "grand jury": 3,
    "grand jury indictment": 4,
    "preliminary hearing": 3,
    "preliminary examination": 3,
    "probable cause hearing": 3,
    "bond hearing": 3,
    "bond set": 3,
    "bond denied": 4,
    "held without bond": 4,
    "no bond": 4,
    "bail hearing": 3,
    "bail set": 3,
    "bail denied": 4,
    "denied bail": 4,
    "bail revoked": 4,
    "remanded": 3,
    "pretrial": 3,
    "pre-trial": 3,
    "pretrial hearing": 3,
    "pretrial conference": 3,
    "status hearing": 3,
    "motion hearing": 3,
    "motion to suppress": 4,
    "motion to dismiss": 4,
    "competency hearing": 4,
    "competency evaluation": 4,
    "mental evaluation": 3,
    "fitness to stand trial": 4,
    "extradited": 3,
    "extradition": 3,
    "detention hearing": 3,
    "initial appearance": 3,
    "first appearance": 3,
    # ---- Charges / legal process ----
    "charged with": 4,
    "charged in": 3,
    "charges filed": 4,
    "additional charges": 4,
    "upgraded charges": 4,
    "reduced charges": 4,
    "charges dropped": 4,
    "charges dismissed": 4,
    "count of": 3,
    "counts of": 3,
    "arrested": 3,
    "arrested for": 3,
    "arrest made": 3,
    "placed under arrest": 3,
    "taken into custody": 3,
    "booked into jail": 3,
    "booked into": 3,
    "booking photo": 3,
    "mugshot": 3,
    "mug shot": 3,
    "felony": 3,
    "felony charge": 4,
    "felony count": 4,
    "misdemeanor": 2,
    "first degree": 4,
    "first-degree": 4,
    "second degree": 3,
    "second-degree": 3,
    "third degree": 3,
    "third-degree": 3,
    "capital murder": 5,
    "capital offense": 5,
    "aggravated": 3,
    "premeditated": 4,
    "with intent": 3,
    "malice aforethought": 5,
    "special circumstances": 4,
    "enhancement": 3,
    "hate crime enhancement": 4,
    "firearm enhancement": 3,
    "gang enhancement": 3,
    # ---- Sentencing / post-trial / appeals ----
    "probation": 3,
    "parole": 3,
    "parole hearing": 4,
    "parole denied": 4,
    "parole board": 3,
    "prison": 3,
    "penitentiary": 3,
    "incarcerated": 3,
    "imprisoned": 3,
    "behind bars": 3,
    "locked up": 2,
    "restitution": 3,
    "community service": 2,
    "house arrest": 3,
    "ankle monitor": 3,
    "sex offender registry": 4,
    "registered sex offender": 4,
    "appeal": 3,
    "appealed": 3,
    "appeals court": 3,
    "appellate court": 3,
    "overturned": 4,
    "reversed": 3,
    "upheld": 3,
    "resentenced": 4,
    "new trial": 4,
    "post-conviction": 3,
    "habeas corpus": 3,
    "exonerated": 5,
    "exoneration": 5,
    "wrongful conviction": 5,
    "innocence project": 5,
    # ---- Legal actors ----
    "prosecutor": 3,
    "prosecutors": 3,
    "prosecution": 3,
    "district attorney": 3,
    "assistant district attorney": 3,
    "state attorney": 3,
    "attorney general": 3,
    "u.s. attorney": 3,
    "county attorney": 3,
    "solicitor": 2,
    "defense attorney": 3,
    "defense lawyer": 3,
    "defense counsel": 3,
    "defense team": 3,
    "public defender": 3,
    "court-appointed": 3,
    "court appointed": 3,
    "judge": 2,
    "presiding judge": 3,
    "chief judge": 3,
    "magistrate": 2,
    "justice": 2,
    "jury": 3,
    "jurors": 3,
    "jury foreman": 3,
    "jury foreperson": 3,
    "bailiff": 2,
    "clerk of court": 2,
    "victim advocate": 3,
    "victim impact statement": 5,
    "victim impact": 4,
    # ---- Investigation ----
    "investigation": 2,
    "under investigation": 3,
    "criminal investigation": 3,
    "ongoing investigation": 2,
    "fbi investigation": 4,
    "federal investigation": 4,
    "internal affairs": 4,
    "internal investigation": 4,
    "special prosecutor": 4,
    "independent investigation": 4,
    "task force": 3,
    "cold case unit": 4,
    "detective": 2,
    "detectives": 2,
    "investigator": 2,
    "investigators": 2,
    "lead detective": 3,
    "homicide detective": 4,
    "homicide unit": 4,
    "crime lab": 3,
}

CRIME_SEVERITY_KEYWORDS = {
    # ---- Homicide / death ----
    "murder": 5,
    "murdered": 5,
    "murderer": 5,
    "homicide": 5,
    "manslaughter": 5,
    "involuntary manslaughter": 5,
    "voluntary manslaughter": 5,
    "vehicular manslaughter": 5,
    "vehicular homicide": 5,
    "criminally negligent homicide": 5,
    "negligent homicide": 5,
    "killed": 4,
    "killing": 4,
    "slain": 4,
    "slaying": 4,
    "death": 3,
    "died": 3,
    "deadly": 3,
    "lethal": 3,
    "fatal": 4,
    "fatality": 4,
    "fatal shooting": 5,
    "fatally shot": 5,
    "fatally stabbed": 5,
    "fatally beaten": 5,
    "shot and killed": 5,
    "shot to death": 5,
    "shot dead": 5,
    "stabbed to death": 5,
    "beaten to death": 5,
    "strangled to death": 5,
    "strangled": 4,
    "strangulation": 4,
    "suffocated": 4,
    "suffocation": 4,
    "asphyxiation": 4,
    "drowned": 4,
    "bludgeoned": 4,
    "dismembered": 5,
    "decapitated": 5,
    "burned alive": 5,
    "set on fire": 4,
    "poisoned": 4,
    "poisoning": 4,
    "overdose death": 4,
    "wrongful death": 5,
    # ---- Shooting ----
    "shooting": 4,
    "gunshot": 4,
    "gunfire": 4,
    "gunman": 4,
    "shooter": 4,
    "active shooter": 5,
    "shots fired": 4,
    "opened fire": 5,
    "fired shots": 4,
    "exchanged gunfire": 5,
    "gun violence": 4,
    "firearm": 3,
    "handgun": 3,
    "rifle": 3,
    "shotgun": 3,
    "assault rifle": 4,
    "ar-15": 4,
    "semi-automatic": 3,
    "automatic weapon": 4,
    # ---- Violent crime ----
    "stabbing": 4,
    "stabbed": 4,
    "knife attack": 4,
    "armed robbery": 4,
    "robbery": 3,
    "robbed": 3,
    "home invasion": 4,
    "burglary": 3,
    "break-in": 3,
    "carjacking": 4,
    "carjacked": 4,
    "kidnapping": 5,
    "kidnapped": 5,
    "abduction": 5,
    "abducted": 5,
    "held captive": 5,
    "hostage": 5,
    "hostage situation": 5,
    "standoff": 4,
    "barricade": 4,
    "barricaded": 4,
    "attempted murder": 5,
    "attempted homicide": 5,
    "assault with a deadly weapon": 5,
    "assault and battery": 4,
    "aggravated battery": 4,
    "battery": 3,
    "attack": 3,
    "attacked": 3,
    "violent attack": 4,
    "brutal attack": 4,
    "unprovoked attack": 4,
    "random attack": 4,
    "ambush": 4,
    "road rage": 4,
    "hit and run": 3,
    "hit-and-run": 3,
    "vehicular assault": 4,
    "dui": 3,
    "dwi": 3,
    "drunk driving": 3,
    "intoxication manslaughter": 5,
    "intoxication assault": 4,
    # ---- Abuse / exploitation ----
    "child abuse": 5,
    "child neglect": 5,
    "child endangerment": 5,
    "child cruelty": 5,
    "cruelty to children": 5,
    "child molestation": 5,
    "molestation": 5,
    "molested": 5,
    "pedophile": 5,
    "child pornography": 5,
    "child sexual abuse material": 5,
    "csam": 5,
    "child exploitation": 5,
    "exploitation of a child": 5,
    "indecency with a child": 5,
    "injury to a child": 5,
    "shaken baby": 5,
    "shaken baby syndrome": 5,
    "failure to protect": 4,
    "sexual assault": 5,
    "sexual abuse": 5,
    "sexual battery": 5,
    "rape": 5,
    "raped": 5,
    "rapist": 5,
    "sexual predator": 5,
    "sex crime": 5,
    "sex offense": 5,
    "sex offender": 5,
    "indecent assault": 5,
    "indecent exposure": 3,
    "lewd conduct": 3,
    "lewd and lascivious": 4,
    "statutory rape": 5,
    "sexual misconduct": 4,
    "domestic violence": 4,
    "domestic assault": 4,
    "domestic abuse": 4,
    "intimate partner violence": 4,
    "spousal abuse": 4,
    "family violence": 4,
    "strangulation": 4,
    "protective order violation": 3,
    "restraining order violation": 3,
    "aggravated assault": 4,
    "felony assault": 4,
    "human trafficking": 5,
    "sex trafficking": 5,
    "labor trafficking": 4,
    "forced labor": 4,
    "elder abuse": 4,
    "elder neglect": 4,
    "abuse of vulnerable adult": 4,
    "animal cruelty": 3,
    "animal abuse": 3,
    "torture": 5,
    "tortured": 5,
    # ---- Use of force / police ----
    "use of force": 5,
    "excessive force": 5,
    "unreasonable force": 5,
    "deadly force": 5,
    "lethal force": 5,
    "officer-involved shooting": 5,
    "officer involved shooting": 5,
    "police shooting": 5,
    "deputy-involved shooting": 5,
    "deputy involved shooting": 5,
    "trooper-involved shooting": 5,
    "police brutality": 5,
    "police misconduct": 4,
    "police corruption": 4,
    "badge abuse": 4,
    "civil rights violation": 5,
    "section 1983": 4,
    "qualified immunity": 4,
    "in-custody death": 5,
    "in custody death": 5,
    "died in custody": 5,
    "died in jail": 5,
    "died in prison": 4,
    "died in police custody": 5,
    "custodial death": 5,
    "jail death": 5,
    "prison death": 4,
    "taser": 4,
    "tased": 4,
    "tasered": 4,
    "pepper spray": 3,
    "pepper sprayed": 3,
    "choke hold": 5,
    "chokehold": 5,
    "knee on neck": 5,
    "restrained": 3,
    "hogtied": 5,
    "prone restraint": 5,
    "positional asphyxia": 5,
    "wrongful death": 5,
    "wrongful arrest": 4,
    "false arrest": 4,
    "false imprisonment": 4,
    "planted evidence": 5,
    "framed": 4,
    "cover-up": 5,
    "coverup": 5,
    # ---- Major crime / organized ----
    "mass shooting": 5,
    "mass murder": 5,
    "mass casualty": 5,
    "school shooting": 5,
    "church shooting": 5,
    "workplace shooting": 5,
    "serial killer": 5,
    "serial murder": 5,
    "serial rapist": 5,
    "spree": 4,
    "killing spree": 5,
    "cold case": 4,
    "unsolved murder": 4,
    "unsolved case": 3,
    "unidentified remains": 3,
    "arson": 4,
    "arsonist": 4,
    "set fire": 3,
    "firebombed": 5,
    "firebombing": 5,
    "explosion": 4,
    "bomb": 4,
    "bombing": 5,
    "bomb threat": 3,
    "ied": 4,
    "improvised explosive": 5,
    "hate crime": 5,
    "hate-motivated": 5,
    "bias crime": 4,
    "terrorism": 5,
    "terrorist": 5,
    "domestic terrorism": 5,
    "extremist": 4,
    "drug trafficking": 4,
    "drug dealer": 3,
    "drug ring": 4,
    "drug cartel": 5,
    "narcotics": 3,
    "fentanyl": 3,
    "meth lab": 4,
    "drug bust": 3,
    "drug operation": 3,
    "conspiracy": 3,
    "criminal conspiracy": 4,
    "racketeering": 4,
    "rico": 4,
    "organized crime": 4,
    "crime ring": 4,
    "gang-related": 3,
    "gang related": 3,
    "gang member": 3,
    "gang violence": 4,
    "gang shooting": 4,
    "money laundering": 3,
    "fraud": 2,
    "embezzlement": 3,
    "extortion": 4,
    "blackmail": 3,
    "identity theft": 2,
    "wire fraud": 3,
    "mail fraud": 3,
    "ponzi scheme": 3,
    "corruption": 3,
    "public corruption": 4,
    "bribery": 3,
    # ---- Missing / endangered ----
    "missing person": 3,
    "missing child": 4,
    "missing woman": 3,
    "missing man": 3,
    "disappeared": 3,
    "amber alert": 4,
    "silver alert": 3,
    "endangered missing": 4,
    "found dead": 4,
    "found deceased": 4,
    "body found": 4,
    "remains found": 4,
    "human remains": 4,
    "shallow grave": 5,
    "unmarked grave": 5,
    "clandestine grave": 5,
}


def compute_prescore(
    article_text: str,
    url: str = "",
    region_id: str = "",
) -> dict:
    """
    Compute a 0-100 artifact likelihood pre-score.

    Returns dict with:
      score: int (0-100)
      matches: list of matched keywords
      breakdown: dict of score components
    """
    text_lower = article_text.lower()
    score = 0
    matches = []
    breakdown = {}

    # Artifact keywords
    artifact_pts = 0
    for kw, pts in ARTIFACT_KEYWORDS.items():
        if kw in text_lower:
            artifact_pts += pts
            matches.append(kw)
    artifact_pts = min(artifact_pts, 45)  # cap
    breakdown["artifact_keywords"] = artifact_pts
    score += artifact_pts

    # Video platform URLs in text
    platform_pts = 0
    for platform, pts in VIDEO_PLATFORMS.items():
        if platform in text_lower:
            platform_pts += pts
            matches.append(f"url:{platform}")
    platform_pts = min(platform_pts, 20)
    breakdown["video_platforms"] = platform_pts
    score += platform_pts

    # Lifecycle indicators
    lifecycle_pts = 0
    for kw, pts in LIFECYCLE_KEYWORDS.items():
        if kw in text_lower:
            lifecycle_pts += pts
            matches.append(f"lifecycle:{kw}")
    lifecycle_pts = min(lifecycle_pts, 15)
    breakdown["lifecycle"] = lifecycle_pts
    score += lifecycle_pts

    # Crime severity signals
    severity_pts = 0
    for kw, pts in CRIME_SEVERITY_KEYWORDS.items():
        if kw in text_lower:
            severity_pts += pts
            matches.append(f"severity:{kw}")
    severity_pts = min(severity_pts, 15)
    breakdown["crime_severity"] = severity_pts
    score += severity_pts

    # Jurisdiction bonuses
    jurisdiction_pts = 0
    if region_id:
        try:
            portals = _get_portals()
            if portals["is_florida"](region_id):
                jurisdiction_pts += 10
                matches.append("florida_sunshine")
            if portals["has_court_video"](region_id):
                jurisdiction_pts += 10
                matches.append("court_video_capable")

            config = portals["portals"].get(region_id, {})
            for agency in config.get("agencies", []):
                abbrev = agency.get("abbrev", "").lower()
                if abbrev and abbrev in text_lower:
                    jurisdiction_pts += 10
                    matches.append(f"agency:{abbrev}")
                    break
        except Exception:
            pass

    jurisdiction_pts = min(jurisdiction_pts, 20)
    breakdown["jurisdiction"] = jurisdiction_pts
    score += jurisdiction_pts

    return {
        "score": min(score, 100),
        "matches": matches,
        "breakdown": breakdown,
    }
